---
- hosts: "{{ host }}"
  become: true
  become_method: sudo
  tasks:
    - name: Extend the logical volume
      command:
        cmd: lvextend -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv
    - name: Resize the filesystem
      command:
        cmd: resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv
